# wfp, 6/6
# simple list stuff

my_list = [1,'a',3.14]
print("my_list consists of: ",my_list)
print()

print("Operations similar to strings")
print("Concatenation")
print("my_list + ['bill'] equals: ", my_list + ["bill"])
print()
print("Repeat")
print("my_list * 3 equals: ", my_list * 3)
print()
print("Indexing")
print("1st element is my_list[0]: ",my_list[0])
print("last element is my_list[-1]: ", my_list[-1])
print()
print("Slicing")
print("First two elements are my_list[0:2]: ",my_list[0:2])
print("Last two elements are my_list[-2:]: ",my_list[-2:])
print("Slice assignment, my_list[:2]=[]: ")
my_list[:2] = []
print("my_list is: ",my_list)
print()
print("Length")
print("Length is len(my_list): ",len(my_list))
print()
print("New stuff, which modifies the list (not for strings)")
print("Append element to the end, my_list.append(True): ")
my_list.append(True)
print("my_list is: ",my_list)
print("Append list into the list, my_list.append([5,6]): ")
my_list.append([5,6])
print("my_list is: ",my_list)
print()
print("Extend, can append all elements in a list")
print("Extend single element to the end, my_list.extend('z'): ")
my_list.extend('z')
print("my_list is: ",my_list)
print("Extend a list of elements, my_list.extend([5,6,7]): ")
my_list.extend([5,6,7])
print("my_list is: ",my_list)
print()
print("Delete elements")
print("Delete the first element, del my_list[0]: ")
del(my_list[0])
print("my_list is: ",my_list)
print("Delete last 4 elements, del my_list[-4:]: ")
del(my_list[-4:])
print("my_list is: ",my_list)
